version: "3"

volumes:
  mysql_data:
    driver: local

services:
  apisix-dashboard:
    image: pkafr0911/apisix-dashboard-viettel-theme:latest
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    user: root
    restart: always
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:4000"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:4000"
    ports:
      - "4000:4000/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
